import Head from 'next/head'
import Image from 'next/image'
import Checkout from '../components/Checkout/Checkout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Demo: <a href="https://nextjs.org">Next.js</a> <br />with <a href="https://stripe.com/">Stripe</a>
        </h1>

        <div className={styles.content}>
          <Checkout />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://medium.com/@bdan-m"
          target="_blank"
          rel="noopener noreferrer"
        >
          Demo Created by&nbsp;<strong>Brendan Mullins</strong>
        </a>
      </footer>
    </div>
  )
}
